lidar:
  laser:
    msh: 'package://pollo_description/meshes/laser.dae'
    x: 0
    y: 0
    z: 0.05  
    visualize: true
    min_angle: 0.83
    max_angle: 2.311592
    min_range: 0.10
    max_range: 10.0
