footprint: [[0.35, 0.35], [0.35, -0.35],[-0.35, 0.35], [-0.35, -0.35]]

map_topic: map
subscribe_to_updates: true

obstacle_layer:
    enabled: true

    obstacle_range: 3.0 # 規劃時考慮幾公尺內的障礙物
    raytrace_range: 3.5 # 清除幾公尺內的障礙物

    # max_obstacle_height: 0.5 # 障礙物最大高度
    # min_obstacle_height: 0.0 # 障礙物最小高度
    # unknown_threshold: 15 # 未知區域的閥值
    # mark_threshold: 0 # 標記區域的閥值
    # combination_method: 1 
    # track_unknown_space: true
    # origin_z: 0.0
    # z_resolution: 0.2
    # z_voxels: 2
    # publish_voxel_map: false
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: laser_link, data_type: LaserScan, topic: pollo/laser/scan, marking: true, clearing: true}

inflation_layer:
    enabled: true
    cost_scaling_factor: 1
    inflation_radius: 0.26

static_layer:
    enabled: true